# Generated by Django 5.1.5 on 2025-07-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_collectionfeaturedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfeaturedimage',
            name='image',
            field=models.ImageField(upload_to='store/collections/images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/prdoucts/images'),
        ),
    ]
