# Generated by Django 5.1.5 on 2025-07-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_product_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Collection',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Promotions',
            new_name='promotions',
        ),
    ]
