# Generated by Django 5.1.5 on 2025-02-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaggedI',
            new_name='TaggedItem',
        ),
    ]
